# Generated by Django 3.2.6 on 2021-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAccessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('item_sent', models.PositiveIntegerField(default=50)),
                ('last_access_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
